version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/ruby
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          EDITOR: vim
          RAILS_ENV: test
    steps:
      - checkout

      - run:
          name: Environment Setup
          command: |
            printf "%s\n" 'export CI_GIT_VERSION=$(cat ".git-version" | tr -d "\n")' >> $BASH_ENV
            printf "%s\n" 'export CI_RUBY_VERSION=$(cat ".ruby-version" | tr -d "\n")' >> $BASH_ENV

      - type: cache-restore
        name: Git Restore
        key: git-{{checksum ".git-version"}}

      - run:
          name: Git Install
          command: |
            sudo apt-get install build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext
            curl https://mirrors.edge.kernel.org/pub/software/scm/git/git-$CI_GIT_VERSION.tar.gz > ../git-$CI_GIT_VERSION.tar.gz
            cd ..
            tar --extract --gzip --verbose --file git-$CI_GIT_VERSION.tar.gz
            cd git-$CI_GIT_VERSION
            ./configure
            make prefix=/usr all
            sudo make prefix=/usr install

      - type: cache-save
        name: Git Store
        key: git-{{checksum ".git-version"}}
        paths:
          - ../git-$CI_GIT_VERSION

      - type: cache-restore
        name: Ruby Restore
        key: ruby-{{checksum ".ruby-version"}}

      - run:
          name: Ruby Install
          command: |
            cd ..
            curl https://cache.ruby-lang.org/pub/ruby/${CI_RUBY_VERSION::-2}/ruby-$CI_RUBY_VERSION.tar.gz > ruby-$CI_RUBY_VERSION.tar.gz
            tar --extract --gzip --verbose --file ruby-$CI_RUBY_VERSION.tar.gz
            cd ruby-$CI_RUBY_VERSION
            ./configure
            make
            make update-gems
            make extract-gems
            sudo make install

      - type: cache-save
        name: Ruby Store
        key: ruby-{{checksum ".ruby-version"}}
        paths:
          - ../ruby-$CI_RUBY_VERSION

      - type: cache-restore
        name: Bundler Restore
        key: bundler-{{checksum "git_plus.gemspec"}}

      - run:
          name: Bundler Install
          command: |
            gem update --system
            bundle config set path "vendor/bundle"
            bundle install

      - type: cache-save
        name: Bundler Store
        key: bundler-{{checksum "git_plus.gemspec"}}
        paths:
          - vendor/bundle

      - run:
          name: Build
          command: |
            sed -i 's/ rubycritic//g' Rakefile
            bundle exec rake
